#!/bin/bash

{
  echo "Checking to see if stack exists"
  stack=aws cloudformation describe-stacks --stack-name "Codesplain-$1"

 } || {
   echo "Creating Stack"
   # If stack doesn't exist
  aws cloudformation deploy --template-file \
    ./serverless-output-sandbox.yaml \
    --stack-name "Codesplain-$1" \
    --parameter-overrides EnvVersion="$1" \
    S3Version="sandbox/$1" \
    ClientSecret="$2" \
    ClientID="$3" \
    --region us-west-2
  exit 0
 }

 stackStatus=$(echo $(aws cloudformation describe-stacks --stack-name "Codesplain-$1") | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["Stacks"][0]["StackStatus"]')

if [[ $stackStatus == "ROLLBACK_COMPLETE" ]]; then
  aws cloudformation delete-stack --stack-name "Codesplain-$1"
fi

# If stack exists
aws cloudformation update-stack --stack-name "Codesplain-$1" \
  --parameters ParameterKey=S3Version,ParameterValue="dev/$CIRCLE_SHA1" \
  ParameterKey=EnvVersion,ParameterValue="$1" \
  ParameterKey=S3Version,ParameterValue="sandbox/$1" \
  ParameterKey=ClientSecret,ParameterValue="$2" \
  ParameterKey=ClientID,ParameterValue="$3" \
   --use-previous-template \
   --region us-west-2
