#!/bin/bash

################################################################################
# This script zips up the lambdas and their dependencies, and pushes them all  #
# to Amazon S3 buckets.                                                        #
################################################################################

function pushZipsToS3 {
  printf "Pushing lambdas to S3 bucket: $1\n"
  aws s3 sync zips s3://$1
}

make all
pushZipsToS3 $1
