#!/bin/bash

featureBranch=$(echo $(echo \
$(curl https://api.github.com/repos/maryvilledev/codesplain-lambdas/git/commits/$1) \
| python -i $PWD/featureBranchName.py  "Merge pull request #65 from maryvilledev/lambdaWhiteList log and change bool to string"))

aws cloudformation delete-stack --stack-name "CodesplainFeature-featureBranch"
