#!/bin/bash

### Script to run the API tests ###

cd "$(dirname "$0")"

function run {
  python -m unittest -v $1
}

run auth.test_endpoint.TestEndpoint.run_tests && \
run parsers.test_endpoint.TestEndpoint.run_tests && \
run mappings.test_endpoint.TestEndpoint.run_tests && \
run users.user_id.snippets.test_endpoint.TestEndpoint.run_tests && \
run users.user_id.snippets.snippet_id.test_endpoint.TestEndpoint.run_tests
